version: '3.8'

services:
  parser_api:
    build: ./parsers_api
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - /LOG/parser_api:/app/logs
    networks:
      - app_network

  parser_bot:
    build: ./parser_bot
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /LOG/parser_bot:/app/logs
    networks:
      - app_network

  service_update:
    build: ./service_update_price
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /LOG/service_update_price:/app/logs
    networks:
      - app_network

  currency_bot:
    build: ./currency_bot
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /LOG/currency_bot:/app/logs
    networks:
      - app_network

networks:
  app_network:
