version: '3.8'

services:
  parsers_api:
    container_name: parsers_api
    build: ./parsers_api
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - /LOG/parser_api:/app/logs
    networks:
      - parsemotoequipment_app_network

  parser_bot:
    container_name: parser_bot
    build: ./parser_bot
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /LOG/parser_bot:/app/logs
    networks:
      - parsemotoequipment_app_network

  service_update_price:
    container_name: service_update_price
    build: ./service_update_price
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /LOG/service_update_price:/app/logs
    networks:
      - parsemotoequipment_app_network

  currency_bot:
    container_name: currency_bot
    build: ./currency_bot
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /LOG/currency_bot:/app/logs
    networks:
      - parsemotoequipment_app_network

networks:
  parsemotoequipment_app_network:
    driver: bridge
