button_cooke_accept_xpath = "//button[@id='lgcookieslaw_accept']"
name_xpath = "//h1"
id_table_spec = "table-data-sheet-container"
product_descriptions_xpath = "//*[@id='product-description']"
link_photo_xpath = "//div[contains(@class, 'swiper-slide')]/a"
colors_xpath = "//*[@id='color_to_pick_list']//li"
child_element_color_xpath = ".//a/div"
photos_slider_xpath = "//div[contains(@class, 'swiper-slide')]"
sizes_xpath = "//*[@class='attribute_list']/ul//li[input]"
input_size_xpath = "./input"
id_price = "our_price_display"
price_xpath = "//*[@id='our_price_display']"
input_count_xpath = "//*[@id='quantity_wanted']"
button_add_xpath = "//*[contains(@class,'button-plus product_quantity_up')]"
id_sku = "product_reference"
class_sku = "editable"
header_xpath = "//header"
promo_xpath = "//*[@id='uniform-auto_add_promo']"
promo_checkbox_xpath = "//*[@id='uniform-auto_add_promo']/span"
cooke_accept_banner_xpath = "//*[@id='lgcookieslaw_banner']"
